name: Go build
on: push
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
      - name: Format
        run: test -z "gofmt -s -l ."
      - name: Lint
        run: |
          GOBIN=$PWD/bin go install golang.org/x/lint/golint
          ./bin/golint ./...
